apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image
  namespace: default
spec:
  params:
    - name: IMAGE
      description: "crygt/backend:v4"
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=Dockerfile"
        - "--context=dir://$(workspaces.source.path)"
        - "--destination=$(params.IMAGE)"
