apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-build-docker-image
  namespace: default
spec:
  pipelineSpec:
    params:
      - name: IMAGE
        type: string
        default: "crygt/backend:v4"
    workspaces:
      - name: shared-workspace
    tasks:
      - name: build-image
        taskRef:
          name: build-docker-image
        params:
          - name: IMAGE
            value: "$(params.IMAGE)"
        workspaces:
          - name: source
            workspace: shared-workspace
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: <tu-pvc>   